[markup]
#  defaultMarkdownHandler = 'goldmark'
  [markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 2
#  [markup.goldmark]
#    [markup.goldmark.renderer]
#      hardWraps = false
#      unsafe = true
#      xhtml = false
 