name: Build for verification

# run when a commit is pushed to "source" branch
on:
  push:
    branches:
    - validate

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout to the commit that has been pushed
    - uses: actions/checkout@v2
      with:
        submodules: true  # Fetch Hugo themes (true OR recursive)
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
    
    # install Hugo
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    # build website
    - name: Build
      run: hugo --gc --minify --cleanDestinationDir --destination "public-integration/"
